### ISSUE TITLE
Actuator Lockup

### ISSUE THREAD

**Issue by JordanKra** [ISC-Project-Phoenix/phnx-brake#3]
After basic testing with a Xbox One controller using ROS + interface board to control brake_ecu there appears to be an issue where rapidly bringing the brake from max position to min position can lead to to actuator getting stuck at full or near full brake and ceasing to respond to additional commands and needing to be restarted.

**Comment by JordanKra** [comment]
After testing on the other actuator this seems to only be prevalent on the actuator with wireless capabilities as the issue doesn't seem to arise on the non-wireless actuator. Considering the problematic actuator was less performant overall in the first place that could be what is causing the issue. Ill be leaving this issue open until more through testing can be done as well as testing with the actual wheel and pedal setup.

**Comment by andyblarblar** [comment]
This was confermed to just be the other actuator
